name: Java CI and .jar build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    strategy:
      matrix:
        jdkversion: [17, 21]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Java ${{ matrix.jdkversion }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdkversion }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -V clean package --file pom.xml

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: AuthMeReloaded-${{ matrix.jdkversion }}
          path: |
            target/AuthMe-*.jar

